#!/bin/bash

function help {
  cat << HELP
NAME:
    template -- Language Templates

SYNOPSIS:
    template <language> [<options>]
    template <language> --help

Languages:
    cpp (c++), rust, ruby, python, kotlin, coq, awk
HELP
  exit 0
}

# when no args
[ $# -eq 0 ] && help

# help
[ "$1" = "--help" -o "$1" = "-h" ] && help

# resolve alias
L=$( cat `dirname $0`/alias | grep "^$1 " | awk '$0=$2' | head -1 )
[ "_$L" == "_" ] && L=$1

# file existence check
if [ ! -f `dirname $0`/lang/$L ] ; then
  cat << WARN
Error: language \`$1\` is unknown (try --help)
WARN
  exit 1
fi

bash `dirname $0`/lang/$L ${@:2:($#-1)}
