#!/bin/bash

MATH_FILE=~/code/awk/awk-procon-library/src/math.awk
if [ -f "$MATH_FILE" ]; then
    cat $MATH_FILE | awk c++
else
    cat <<EOM
function max(x,y){return x<y?y:x}
function min(x,y){return x<y?x:y}
function abs(x){return x<0?-x:x}
function gcd(x,y){return y==0?x:gcd(y,x%y)}
function lcm(x,y){return x/gcd(x,y)*y}
EOM
fi

cat <<EOM
NR==1{
}
NR>1{
}
END{
}
EOM
