#!/bin/bash

function help {
  cat << HELP
NAME:
    template python -- Python Templates

SYNOPSIS:
    template python
HELP
  exit 0
}
[ "_$1" = "_-h" -o "_$1" = "_--help" ] && help

cat << EOF
from queue import Queue


def main():
  n = read(int)


def read(dtype, q=Queue()):
  while q.empty():
    for i in input().split():
      q.put(i)
  return dtype(q.get())


if __name__ == "__main__":
  main()
EOF
