#!/bin/bash

function help {
  cat << HELP
NAME:
    template rust -- Rust Templates

SYNOPSIS:
    template rust

* Scanner クラスの工夫だけ
HELP
  exit 0
}

[ "_$1" = "_-h" -o "_$1" = "_--help" ] && help

cat << EOF
#![allow(unused_imports)]
#![allow(unused_macros)]
use std::cmp::{ min, max };

macro_rules! ewriteln {
    (\$(\$args:expr),*) => { let _ = writeln!(&mut std::io::stderr(), \$(\$args),*); };
}
macro_rules! trace {
    (\$x:expr) => { ewriteln!(">>> {} = {:?}", stringify!(\$x), \$x) };
    (\$(\$xs:expr),*) => { trace!((\$(\$xs),*)) }
}
macro_rules! put {
    (\$x:expr) => { println!("{}", \$x) };
    (\$x:expr, \$(\$xs:expr),*) => { print!("{} ", \$x); put!(\$(\$xs),*) }
}

#[allow(dead_code)]
const M: i64 = 1_000_000_007;

fn main() {
    let mut sc = Scanner::new();
    let n: usize = sc.cin();
    trace!(n);
}

use std::io::{self, Write};
use std::str::FromStr;
use std::collections::VecDeque;

struct Scanner { stdin: io::Stdin, buffer: VecDeque<String>, }
impl Scanner {
    fn new() -> Scanner { Scanner { stdin: io::stdin(), buffer: VecDeque::new() } }
    fn cin<T: FromStr>(&mut self) -> T {
        while self.buffer.len() == 0 {
            let mut line = String::new();
            let _ = self.stdin.read_line(&mut line);
            for w in line.split_whitespace() {
                self.buffer.push_back(String::from(w));
            }
        }
        self.buffer.pop_front().unwrap().parse::<T>().ok().unwrap()
    }
}
EOF
